game:
  num_players: 5
bots:
  - type: RandomBot
    p_call: 0.4
    p_lie: 0.6
  - type: RandomBot
    p_call: 0.2
    p_lie: 0.1
  - type: RandomBot
    p_call: 0.3
    p_lie: 0.2
  - type: RandomBot
    p_call: 0.4
    p_lie: 0.3
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.1
  - type: RandomBot
    p_call: 0.3
    p_lie: 0.6