game:
  num_players: 5
  seed: 42
  experimental_mode: False

bots:
  - type: RandomBot
    name: His Botness
    avatar: ğŸ¦Š
    p_call: 0.2
    p_lie: 0.1
    verbosity: 1
  - type: RandomBot
    name: B0Ttled Up
    avatar: ğŸ¾
    p_call: 0.3
    p_lie: 0.2
    verbosity: 1
  - type: RandomBot
    name: Beep Boop
    p_call: 0.4
    p_lie: 0.3
    avatar: ğŸ¤–
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.1
    name: ChattyBot
    avatar: ğŸ­
    verbosity: 1
  - type: RandomBot
    p_call: 0.3
    p_lie: 0.6
    name: B0Tanical
    avatar: ğŸŒ¼
    verbosity: 1