game:
  num_players: 6
bots:
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.5
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.5
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.5
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.5
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.5
  - type: RandomBot
    p_call: 0.5
    p_lie: 0.5